# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

addons:
  code_climate:
  repo_token: d59bc96dddf8f2e60ec41034a75e7a48fb7db7c04773e1b6e74a0f388c21bde5

before_install:
  - composer self-update
  - pip install --user codecov

# Commands to be run before your environment runs.
before_script:
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script:
  -  php index.php
  -  phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

after_success:
  - codecov

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never
